### ISSUE TITLE
January 27 update tft35  

### ISSUE THREAD

**Issue by Jeripimo** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1576]
X Y and Z position not updated during print

**Comment by oldman4U** [comment]
Marlin emulation I guess.

But it has been working before using which firmware version?

**Comment by Jeripimo** [comment]
It was working before. version TFT35_E3_V3.0.26.x Sep 12 2020
Using this display mode: https://www.reddit.com/r/BIGTREETECH/comments/iphojt/filament_cooling_fan_dont_show_off_on_tft35_e3/

And: fan speed not updating stays 0%

**Comment by radek8** [comment]
> 
> And: fan speed not updating stays 0%

Many times it has already been addressed here.
Read the comments in Config.ini
In Marlin you have to enable the option
REPORT_FAN_CHANGE (in Configuration_adv.h)

**Comment by oldman4U** [comment]
This information is several months old. Updating and reading will solve your problems. And I still don't know if you talk about Marlin or Touchscreen mode.

**Comment by Jeripimo** [comment]
The problem is in touch screen mode using octoprint.
If I enable REPORT_FAN_CHANGE still no fan speed update in touch screen mode.

If printing from sd card in touch screen mode the fan speed is updated.

The internet example was just to show the screen mode I am using, touch screen.
In this mode x y and z position not updated.

Thanks

**Comment by oldman4U** [comment]
In Touchscreen mode, there is no x,y and z shown during print. So I still have no idea what you mean, sorry.

**Comment by Jeripimo** [comment]
If you look at the example in this link you can see the x y and z position
It's the same screen as on my tft35
https://www.reddit.com/r/BIGTREETECH/comments/iphojt/filament_cooling_fan_dont_show_off_on_tft35_e3/

**Comment by oldman4U** [comment]
Yes. But this is the pre print screen. In this case the information that
you print using Octoprint could somehow be important.

In this case I would not answer you because I can not help.

Jeripimo <notifications@github.com> schrieb am Fr. 29. Jän. 2021 um 11:29:

**Comment by kisslorand** [comment]
@Jeripimo 
 Do you have M114_DETAIL enabled in Configuration_adv.h?

**Comment by Jeripimo** [comment]
Do I need to?
Version I am running now no issue only the latest one has that issue

**Comment by kisslorand** [comment]
In the status screen the coordinates are queried every two seconds. For some reason Marlin doesn't answer. Enabling M114_DETAIL wouldn't hurt.
The conditions for the coordinate query are:
* printer connected to the TFT
* printer not in "wait" state
* a previous coordinate query got already an answer from Marlin

**Comment by Jeripimo** [comment]
Ok I'll try thatOn Jan 29, 2021 20:27, kisslorand <notifications@github.com> wrote:
In the status screen the coordinates are queried every two seconds. For some reason Marlin doesn't answer. Enabling M114_DETAIL wouldn't hurt.
The conditions for the coordinate query are:
printer connected to the TFTprinter not in "wait" statea previous coordinate query got already an answer from Marlin

**Comment by kisslorand** [comment]
So?

**Comment by Jeripimo** [comment]
Tried it today.

When enabling M114_DETAIL  my TFT won't connect to the printer even though the baud rate is correct.
Reflashed without M114 and it's ok again

**Comment by kisslorand** [comment]
This is very odd. You should compare your Marlin config files against someone else's working ones.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by Jeripimo** [comment]
Not solved
