### ISSUE TITLE
GD TFT35 V3 E3 firmware build, UBL mesh edit error

### ISSUE THREAD

**Issue by FrozenIceman01** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2782]
The latest GD TFT 35 V3 E3 build on the repository currently does not allow the editing of any other row than the first row of any of the prior created mesh.

I used the prebuilt firmware as well as built my own version in visual studios with the same result.

Step 1:  Flash firmware via SD Card (config, language. En, firmware, and tft35 icon folder)
Step 2:  Preheat extruder to 240 c and bed to 70 c
Step 3:  UBL mesh start, 9x9
Step 4:  Save mesh in slot 0 and 1
Step 5:  Open Mesh edit
Step 6:  attempt to select mesh point on any row below row 1 (fail)

Prior version circa 3 months ago allowed allowed for mesh edit.  However it would periodically throw an m11 or m14 error and wouldn't allow to adjust the mesh point any farther.  Solution would be to save the mesh, power cycle printer, and continue mesh edit until it fails again. 

I have confirmed the March 22nd release of the GD TFT35 e3 v3 firmware did not have this error.  Most commits after March 22 are failed builds.

**Comment by digant73** [comment]
Fixed by #2781

**Comment by FrozenIceman01** [comment]
Latest build tested, issues not resolved.

First issue which is the row column issue is resolved.

Second issue that throws m11 or m14 errors and not allowing mesh adjustment any further is not resolved.

Please re-open.
