### ISSUE TITLE
printer halts on any change during print

### ISSUE THREAD

**Issue by Thijsvanzwam** [bigtreetech/BIGTREETECH-TouchScreenFirmware#837]
### Description

When changing settings like print speed, temperature or fanspeed, the printer stops completely.

### Steps to reproduce

1. print form SD or USB
2. during any layer, change a setting like print speed or fan speed.
3. printer stops and bed and hotted stay hot

**Expected behavior**
well... that the fan speed or print speed change...

**Actual behavior**
printer stalls completely, reset is needed.

### Hardware Variant
BTT TFT35 v3.0
BTT SKR1.4, TMC2209
### TFT Firmware Version & Main Board Firmware details
latest TFT firmware and latest Marlin on SKR1.4. (tested it with older Marlin on mainboard but same issue.)

### Additional Information
The config file is the one provided by the firmware on Github, I did not make any changes. Only config.ini is changed so that is attached.
[config.ini.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4908769/config.ini.zip)

**Comment by oldman4U** [comment]
Hi. Using Master TFT firmware should solve the problem.

**Comment by Thijsvanzwam** [comment]
Hi,  
I have the most recent firmware grom github loaded, is that the master version?

**Comment by oldman4U** [comment]
The precompiled is old. Master is new, includes the fix and has to be compiled by yourself.

**Comment by Thijsvanzwam** [comment]
Ok great, I'll try that!
For some reason I can only find the precompiled ones... Would it be possible you post a link?
thanks in advance!

**Comment by oldman4U** [comment]
When you go to the top of this page you can see „Code“. Click on it opens a
page which allows you to select beteween Master and x26.1. Master is the
correct one which you have to compile in VSC before you can upload it to
your TFT. Have you done this before?

Thijsvanzwam <notifications@github.com> schrieb am Mo. 13. Juli 2020 um
10:13:

**Comment by Thijsvanzwam** [comment]
Yup found it, but when I select the master branch, it is precompiled.
I have uploaded it to the TFT before, and used VSC to compile Marlin for the mainboard.

**Comment by Tygrys-1** [comment]
As the precompiled binaries have been updated recently, you may try current version without building your own.

To build your own you have to download or clone the repository just like with the Marlin.

**Comment by Thijsvanzwam** [comment]
fixed it!
the latest precompiled binaries fixed the issue.
My own compiled one did too!

**Comment by radek8** [comment]
The problem is not fixed.
Try changing the fan speed with the rotary encoder. Fast moving :-(

**Comment by oldman4U** [comment]
@Thijsvanzwam 

Be aware the fan speed is still broken.

**Comment by radek8** [comment]
> @Thijsvanzwam
> 
> Be aware the fan speed is still broken.

Try PR #840 works for me

**Comment by oldman4U** [comment]
Aaaah. It is already available.

Great

Radek <notifications@github.com> schrieb am Di. 14. Juli 2020 um 12:35:

**Comment by Thijsvanzwam** [comment]
Still have the issue that no fan speed is shown during print.
fan runs but shows 0%

**Comment by oldman4U** [comment]
@Thijsvanzwam 

Please open a new ticket and add all information regarding your setup especially the hardware you use and if this ever has been working properly before.

**Comment by radek8** [comment]
> Still have the issue that no fan speed is shown during print.
> fan runs but shows 0%

I couldn't simulate this problem

**Comment by Thijsvanzwam** [comment]
I'll try to reinstall the firmware to see if it changes anything.

**Comment by radek8** [comment]
> I'll try to reinstall the firmware to see if it changes anything.


try this
[BIGTREE_TFT35_V3.0.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4920278/BIGTREE_TFT35_V3.0.26.x.zip)

**Comment by Thijsvanzwam** [comment]
did that, reinstalled it with the precompiled version and it works now.
strange as I used exactly the same version I installed yesterday... But hey... if it works!

Only thing still is that I have to push the reset button te get onboard SD to work. (the one on the mainboard)
Could that have something to do with the TFT booting faster then the SKR mainboard? (just guessing)

**Comment by radek8** [comment]
Boot speed has no effect.
If the display boots, it repeatedly sends a query to Marlin. When Marlin is ready, he will respond with his parameters.

**Comment by Thijsvanzwam** [comment]
[Marlin config.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4920588/Marlin.config.zip)
Ok, i see. then there could be something wrong in Marlin that doesn't send the correct parameters.
I will review my config files again, put them in as attachment for those who would like to take a look at them.

**Comment by radek8** [comment]
If you have Autolevel, get it
#define BABYSTEPPING

**Comment by radek8** [comment]
activate
#define AUTO_REPORT_SD_STATUS

**Comment by Thijsvanzwam** [comment]
> If you have Autolevel, get it
> #define BABYSTEPPING

I do have autolevel, should I activate this option?

**Comment by Thijsvanzwam** [comment]
> activate
> #define AUTO_REPORT_SD_STATUS

ah, forgot that one I see...

**Comment by radek8** [comment]
> > Pokud máte Autolevel, získejte to 
> > #define BABYSTEPPING
> 
> Mám autolevel, měl bych tuto možnost aktivovat?

can tune Z-offset when printing

**Comment by radek8** [comment]
Please close the ticket
